### ISSUE TITLE
Predict Functions

### ISSUE THREAD

**Issue by vatsalag99** [sevamoo/SOMPY#102]
Can you please provide an example of how to use the predict functions in this library? I am a little unclear as to how this would work.

**Comment by vatsalag99** [comment]
To add to my question, would it be possible to utilize this SOM framework to determine which cluster a test sample matched the closest to?

**Comment by sevamoo** [comment]
if you want to find the bmus for (new) data sets, there are several functions: project and find_k_nodes. 
If you want to predict, it is called predict and predict_by
