### ISSUE TITLE
calculate_topographic_error bug

### ISSUE THREAD

**Issue by jeanvahe** [sevamoo/SOMPY#122]
Below calling find_bmu, the paramter data should be normalized data, need change data_raw to _data.

        bmus1 = self.find_bmu(self.data_raw, njb=1, nth=1)
        bmus2 = self.find_bmu(self.data_raw, njb=1, nth=2)

**Comment by sevamoo** [comment]
Thanks and sorry for the very late reply. 
Could you please, send this on a pull request?
Best
Vahid
