### ISSUE TITLE
What is clustering routine ??

### ISSUE THREAD

**Issue by edwardcho** [sevamoo/SOMPY#123]
Hello sir,

Thank you for your site.

I want to cluster for my feature vector list using SOM.

x is my feature vector list.
```python
    import som

    mapsize = [len(x), 1]
    som = sompy.SOMFactory.build(x, mapsize, mask=None, mapshape='planar', lattice='rect', normalization='var', initialization='pca', neighborhood='gaussian', training='batch', name='sompy')
    som.train(n_job=1, verbose='info')

    y_pred_som = som.cluster(n_clusters=n_clusters)
```
How to control mapsize for my data ??
And Is correct clustering routine ??

Thanks,
Edward Cho

**Comment by sevamoo** [comment]
import som

    mapsize = [len(x), 1] --- > use any values here [m1,m2]
    som = sompy.SOMFactory.build(x, mapsize, mask=None, mapshape='planar', lattice='rect', normalization='var', initialization='pca', neighborhood='gaussian', training='batch', name='sompy')
    som.train(n_job=1, verbose='info')

    y_pred_som = som.cluster(n_clusters=n_clusters) -- > choose a number for n_cluster
