### ISSUE TITLE
Som Toolbox Input Missing Values

### ISSUE THREAD

**Issue by rodiegeology** [sevamoo/SOMPY#127]
The Som Toolbox in Matlab accepts the input of data with NaN values at SOM_READ_DATA (on the [missing] optional parameter). I need this implementation to uso SOM for Data Imputation. Is there any tip I can get on how to implement it on SOMpy?

**Comment by sevamoo** [comment]
You could use simple ideas like median imputer as a quick fix, but IMO the data Imputation is a topic for itself and should be taken care of independently of the next step in your data pipeline (here being SOM training). 
There are a lot of Data Imputation algorithms that I suggest you look for.
