### ISSUE TITLE
How can I use this package on google colab?

### ISSUE THREAD

**Issue by F-Madruga** [sevamoo/SOMPY#128]

**Comment by sevamoo** [comment]
I think we need some help to make this library pip installable!

**Comment by CatChenal** [comment]
There is a solution (tested) without packaging for pip:
```
!pip install git+https://github.com/sevamoo/SOMPY.git
```

**Comment by nanakayhacker** [comment]
Thank you for this great package. It was very useful to me. However I have one problem understanding the component planes. Please I want to grab the actual data generated for the weights that were used to derived the component planes so I can use them for statistical purposes. I want to get the the neural weights use for initialising each input vectir. In your use case, the weights were initialised using pca. I want to get those weight vectors for each wining neuron with corresponding to their input. In summary I want to get the overall array of values for the component planes

**Comment by nanakayhacker** [comment]
Hello  Vahid Moosavi,

Thank you for inventing this great sompy package. It was very useful to me. I have been using it for my article publication and it will be referenced duly.

However I have one problem understanding the component planes. My input variables are many, hence deciphering the patterns to associations just from the component planes is very cumbersome. I need help on the sompy command which I can use to get the results from the component planes so I can do statistical inferences on it.

I want to know if there is a way out to get this problem resolved. I will be glad if my requisition is given the due clarification. 

Counting on your cooperation. Thank you

Best Regards, 
John Owusu

**Comment by nanakayhacker** [comment]
Thank you for this great package. It was very useful to me. However I have one problem understanding the component planes. Please I want to grab the actual data generated for the weights that were used to derive the component planes so I can use them for statistical purposes. I want to get the neural weights used for initialising each input vector. In your use case, the weights were initialised using pca. I want to get those weight vectors for each winning neuron corresponding to their input. In summary I want to get the overall array of values for the component planes

**Comment by sevamoo** [comment]
Seems there was already a solution suggested here.
