### ISSUE TITLE
How to add more data to the trained som

### ISSUE THREAD

**Issue by VaniaM17** [sevamoo/SOMPY#130]
Hello,
I am not a programmer, but i am working on a project related to SOM and I am using your package.
I have a very large data set with 7 variables. Due to the large size, I initially trained my model on only 4 variables. Is it possible to add the remaining variables to the trained model and update the model?

**Comment by sevamoo** [comment]
If you have a data set with the size of (MxN) where M is very large you can always take a sample from the rows for the training (i.e. m1xN) and after training use the "projection" options to find the BMU of all of your data. 
But if you train your SOM with a part of the variables (i.e n1 < N), then you can not add new columns to your trained SOM afterward. If your N is really a large number, then most likely I guess your data is very sparse. Then I suggest you can use some other ways to reduce the dimensionality first by using for example Randomized PCA first. If this is the case, I suggest you look at other approaches such as auto-encoders to get a dense vector first and then use SOM for further analyses.
