### ISSUE TITLE
    w = som.winner(data[x]) 

### ISSUE THREAD

**Issue by akol67** [sevamoo/SOMPY#131]
Dear Sevamoo

The statement above is from MiniSom. 
w = kohonen coordinates
x = index

Do you have a way in your code to produce a list of neurons based on index from original data? 

[(7, 3),
 (7, 0),
 (43, 30),
 (8, 4),
 (43, 30),

This is useful since we can plot neurons according our needs

**Comment by sevamoo** [comment]
I think this [function](https://github.com/sevamoo/SOMPY/blob/3c659bc61cd0576a5ac3a3400e380efe529866d2/sompy/sompy.py#L431) should give what you are looking for.
Best
Vahid
