### ISSUE TITLE
_calculate_ms_and_mpd()

### ISSUE THREAD

**Issue by oliviaguest** [sevamoo/SOMPY#15]
I am trying to understand how ``trainlen`` and related variables are calculated using: ```_calculate_ms_and_mpd```, what does ms and mpd stand for?

I think ideally, I would like to set up my own training to be able to train again after training, as if I am not wrong, neither is possible at the moment - yes?

I will attempt to do this, but there are some bits of the code I don't understand yet.

**Comment by sevamoo** [comment]
The question is how to select the meta-parameters. 
Heres, mpd deals with the number of iterations. mpd is the ratio between number of nodes and number of training data. trainlen is decided based on mpd but in 4 different ways: 
(rough_train or finetune_train)x( initialization == 'random' or self.initialization == 'pca'). the coefficients are chosen logically and based on several experiments.
ms is to decide about the radius in neighborhood search. 
for both of these factors, they are calculated differently if the SOM grid is one dimensional. 

It would be much better if those final coefficients would be input parameters.

**Comment by oliviaguest** [comment]
Thanks that makes sense with what I discovered in the meantime too. So I have modified my version of ```.train``` to allow training length and the initial and final radii to be set from outside the som and to allow multiple training sessions (i.e., weights not reset every time train is run).
