### ISSUE TITLE
How to install library?

### ISSUE THREAD

**Issue by KevinAyuque** [sevamoo/SOMPY#19]
Sorry I'm very new to Python, I usually use pip or a setup.py to install a library. How do you install this one?

**Comment by punyidea** [comment]
This library is pretty simple to install- just drag it into the site-packages folder that your python installation uses. If you don't know where that is, then try looking in the default places where Python is installed.

When you're starting to run this code, you may get some minor errors of the "ImportError" family. If anything like that pops up, it very likely means that you don't have a requisite library installed. Just pip install and you're off!

**Comment by imaculate** [comment]
Hi @punyidea which folder should be put in site-packages, the outer or inner sompy?

**Comment by imaculate** [comment]
Also I think the instructions should have been in the README ... @sevamoo , I can make pull request for that..:)

**Comment by imaculate** [comment]
I have managed to install the inner folder, not sure where to put visualization...

**Comment by sevamoo** [comment]
@imaculate please update the README. Thanks

**Comment by Dummy-gitacc** [comment]
I am unable to install the repo. I have extracted the repo and stored in 'site-packages'. Then I went to my anaconda navigator cmd and used 'python3 setup.py install', but it shows: "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."
What should I do? Could someone please update the readme file and write a step-by-step process of how to install this?
