### ISSUE TITLE
show() Exception: Data must be 1-dimensional

### ISSUE THREAD

**Issue by pedrinimm** [sevamoo/SOMPY#20]
When It tries to show any result from the som like: codebook, cluster, or hitmap the normalisation method estimates the mean and the std with pandas. However since data is not 1 dimensional and exception gets triggered

**Comment by sevamoo** [comment]
could you please show your code?

**Comment by janbalaz** [comment]
Hi,
happened to me as well. Problem was I used regular Python array instead of Numpy array. I wrapped my data as follows:
```
import numpy as np
data = np.array(list_data)
```
Not sure if it's your case as well.
