### ISSUE TITLE
minor typo in /visualization/dotmap.py

### ISSUE THREAD

**Issue by am4002** [sevamoo/SOMPY#23]
Line 66 in /visualization/dotmap.py reads:
`plt.subplots_adjust(hspace=.16, swspace=.05)`

subplots_adjust() has no 'swspace' parameter but it does have a 'wspace', so the line should presumably read:
`plt.subplots_adjust(hspace=.16, wspace=.05)`

This library is great sevamoo, thanks

**Comment by sevamoo** [comment]
Thanks @am4002. Now it is updated.
Best
Vahid
