### ISSUE TITLE
Why the algorithm with njob > 1 is slower than njob = 1?

### ISSUE THREAD

**Issue by jiperez91** [sevamoo/SOMPY#31]
In my PC the algorithm with njob > 1 is slower than njob = 1. Anyone knows why? There is a way to speed up the algorithm?

Thanks!

**Comment by ivallesp** [comment]
Same happens here from Windows 10 and Python 2.7

**Comment by sevamoo** [comment]
@ivallesp  is it still like that with the new update you sent? Best Vahid

**Comment by ivallesp** [comment]
No, I think it is solved!

**Comment by sevamoo** [comment]
Thanks a lot.
