### ISSUE TITLE
In the SOM train function the verbose mode cannot be set to final

### ISSUE THREAD

**Issue by sujaygokhale07** [sevamoo/SOMPY#32]
According to the displayed error below, verbose can only be debug, info or None.

`:param` verbose: verbosity, could be 'debug', 'info' or None
"""
logging.root.setLevel(getattr(logging, verbose.upper()) if verbose else logging.ERROR)

logging.info(" Training...")

AttributeError: 'module' object has no attribute 'FINAL'`

I'm guessing i've installed the wrong version, since i've seen its usage in one of your provided examples. Link: http://nbviewer.jupyter.org/gist/sevamoo/e93699fdb481de1a932b

I've installed SOMPY using: `pip install git+https://github.com/sevamoo/SOMPY.git`

Please let me know how i can fix this. Thanks.

**Comment by sevamoo** [comment]
Hi
The provided example is based on the old version of the library. In the current version, you only have choices of 'debug', 'info' or None.
Best
