### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by oliviaguest** [sevamoo/SOMPY#33]
How would you like the library to be cited, e.g., in a journal publication?

**Comment by sevamoo** [comment]
Thanks for any citation in advance. Unfortunately, there is no published paper on the library so far. 
One simple way which is not encouraged by journals is to put a link to repository in the footnote.
Other wise, seems it is possible to refer to the library like this: 
Authors Names, Project Title, (2015), GitHub repository, https://github.com/charlespwd/project-title
In this case, I think it is fair to mention my name that originally wrote the code and @sebastiandev who modified it into pythonic standard. 
@sebastiandev  what is your full name by the way? :)
@oliviaguest any other suggestion?

**Comment by oliviaguest** [comment]
My suggestion would be to create a CITATION file to avoid some of the confusion that could arise. Read more here: https://www.software.ac.uk/blog/2014-07-30-oh-research-software-how-shalt-i-cite-thee

**Comment by sebastiandev** [comment]
Vahid,

Thats very kind from you. My full name is Sebastian Packmann. I really
appreciate it.
Let me know if you guys need anything.

Thanks
Seba.

**Comment by sevamoo** [comment]
Sorry @oliviaguest I didn't have time yet to read the link you sent. Would be great if any of you @oliviaguest @sebastiandev  could add this new document. 
Thanks a lot.
Best
Vahid

**Comment by oliviaguest** [comment]
Adding a citation file was merely a recommendation. I just want to cite you correctly if/when required, and that's enough info I think - so thanks.

**Comment by sevamoo** [comment]
Hi add these lines to the README file:
Vahid Moosavi and Sebastian Packmann, SOMPY: A Self Organizing Map Library in Python, 2015, available online:https://github.com/sevamoo/SOMPY.
Nevertheless, it doesn't look so standard to me. Anyways thanks @oliviaguest

**Comment by oliviaguest** [comment]
I was talking about a journal article, so it would need to be referenced from within that in the correct referencing style, not in a README file, although obviously that would be available in the github repo. So what you gave above is useful but will not be the final form I would use.

Notwithstanding, I can't promise I will actually use SOMPY in the final version of my model, even though it has some pretty visualisations, because some of the features are opaque to me and some important ones are missing. Either way I presented the work I have done so far using both SOMPY and another SOM library at a conference last week and received positive comments. I'll probably write this after I have left my post at Oxford so within the next 6 months, after I have moved to my new position in London.

**Comment by sevamoo** [comment]
@oliviaguest No worries Olivia
Honestly, I had never thought about it to write a paper on this library as in my opinion, there were new contributions. Feel free to use or not use it and I always would be happy to see this library used in different fields. 
Best
Vahid
P.S.: Congrats for the new position :)

**Comment by oliviaguest** [comment]
Thanks! You don't have to write a paper. I was referring to referencing this repo from a paper. However, I think you could easily write one and send it to http://openresearchsoftware.metajnl.com/ if you want! :smile:
