### ISSUE TITLE
problem with running the examples from notebooks

### ISSUE THREAD

**Issue by kroham** [sevamoo/SOMPY#52]
Hello,
I get this error when I try to run the example from notebook 1:

Traceback (most recent call last):
  File "sompy.py", line 7, in <module>
    import sompy as SOM
  File "/home/kroham/sompy.py", line 27, in <module>
    sm = SOM.SOM('sm', Data, mapsize = [msz0, msz1],norm_method = 'var',initmethod='pca')
TypeError: 'module' object is not callable

Are the notebook examples still working?
Thanks in advance.

**Comment by sevamoo** [comment]
As it is written: "The following examples, need some modifications, since the library has been modified. However, it should be easy to figure out how to use them."
if you compare it with https://gist.github.com/sevamoo/035c56e7428318dd3065013625f12a11
should not be difficult to find out the error.
