### ISSUE TITLE
Using SOMPY for text clustering?

### ISSUE THREAD

**Issue by Landre** [sevamoo/SOMPY#65]
Hi I'm new to SOM's and stumbled across your SOMPY library. Your examples work pretty well so far but I wonder if I also can use this library to cluster texts and how the feature vectors for training etc should look like to achieve that. Do you have a guess/hint or, by any chance, an example? My goal is to use the data of Grimm's fairytales. I want to cluster the text by its affiliation to a fairytale. If I get a new text-input, I want to get a SOM that clusters text in a way, that I can see the relations between the input text and fairytales. Is this possible?

Greetings

**Comment by sevamoo** [comment]
If you manage to convert your text to a data matrix, where rows are your texts and columns are the chosen feature, SOM will do its part. Your question is out of the scope this library. Take a look at gensim library examples for vectorization of texts.
