### ISSUE TITLE
Bug - self._bmu[0] not updated at last training iteration, BmuHitsView visualization incorrect

### ISSUE THREAD

**Issue by beckrob** [sevamoo/SOMPY#83]
Hello,

I believe that the BMU stored for the training data in self._bmu[0] is not updated after the last training iteration. 
(https://github.com/sevamoo/SOMPY/blob/master/sompy/sompy.py, line 342-343, 360-361)

As BmuHitsView uses self._bmu[0] in visualizing the hit count, the plot will be out of sync with the latest version of the SOM map.
(https://github.com/sevamoo/SOMPY/blob/master/sompy/visualization/bmuhits.py, line 24)

As a side effect, the reported quantization error, based on self._bmu[1], may also be one iteration behind.

In this example, I train a SOM with an arbitrary trainingArray and mapSize, then plot the hit counts.
```
import sompy
from sompy.visualization.bmuhits import BmuHitsView

somModel=sompy.SOMFactory().build(trainingArray,
                                  mapSize,
                                  normalization = 'var', 
                                  initialization='random', 
                                  component_names=fieldsUsedSOM)

somModel.train(n_job=4, verbose=None, train_rough_len=3, train_finetune_len=6)

vhts  = BmuHitsView(200,200,"Hits Map",text_size=12)
vhts.show(somModel, anotate=True, onlyzeros=False, labelsize=8, cmap="Greys", logaritmic=False)
```

I then compute the matching BMUs for the same trainingArray, in two ways.
```
indexes1=somModel.project_data(trainingArray)
indexes2=somModel.find_bmu(somModel._normalizer.normalize(trainingArray), njb=4)

indexesMatch=np.all(indexes1==indexes2[0])
```

indexesMatch will evaluate to be True, so the two approaches give the same, correct BMU indices. Both find_bmu (line 390) and project_data (line 441) use the updated codebook.matrix (line 343).
(https://github.com/sevamoo/SOMPY/blob/master/sompy/sompy.py)

However, self._bmu[0] will be clearly different from indexes1 and indexes2[0], and this is what I believe to be the key indicator of the bug.

A potential (untested) fix I see would be to pass a flag to the last-executed _batchtrain in finetune_train to run this at line 359:
(https://github.com/sevamoo/SOMPY/blob/master/sompy/sompy.py)
```
if lastFlag:
    bmu = self.find_bmu(data, njb=njob)
```
followed by what is already there:
```
bmu[1] = np.sqrt(bmu[1] + fixed_euclidean_x2)
self._bmu = bmu
```

Of course, this snippet suggests that the quantization error may also be reported for the previous iteration, as bmu[1] also comes from an earlier find_bmu call. I did not thoroughly go through the logic of this, though.

Thanks for this useful package,
Robert Beck

**Comment by frsnjung** [comment]
You are right about that bug I think, I also noticed this when I used the find_bmu method outside of sompy for the same Training data set. I fixed it in my local version by adding an extra line. You can open a pull request for your fix if you test your code successfully

**Comment by ivallesp** [comment]
I add a function for calculating the quantization error which I think would solve the issue
