### ISSUE TITLE
How to save model ? 

### ISSUE THREAD

**Issue by SchofieChen** [sevamoo/SOMPY#85]
I can't find the function could save model after training

**Comment by beckrob** [comment]
There is no built-in function, however, you can use the joblib package to pickle the trained SOM object in memory and save to a file:
`joblib.dump(somModel, 'path/filename.pkl')`

Loading it back into memory is similarly simple:
`somModel=joblib.load('path/filename.pkl')`

These functions have additional parameters that can solve compatibility issues, e.g. if you need to load from other Python versions. I haven't tested this myself, though.

**Comment by SchofieChen** [comment]
thanks you ! it worked
