### ISSUE TITLE
explain of update_codebook_voronoi && why _distance_matrix doesn't change?

### ISSUE THREAD

**Issue by johnnykokos** [sevamoo/SOMPY#88]
Dear all,
Could anybody help me with the implementation understanding of update_codebook_voronoi function? I have several questions about it:
```
        ...
        P = csr_matrix((val, (row, col)), shape=(self.codebook.nnodes,self._dlen))
        S = P.dot(training_data) 

        # neighborhood has nnodes*nnodes and S has nnodes*dim
        # ---> Nominator has nnodes*dim
        nom = neighborhood.T.dot(S)
        nV = P.sum(axis=1).reshape(1, self.codebook.nnodes)
        denom = nV.dot(neighborhood.T).reshape(self.codebook.nnodes, 1)
        new_codebook = np.divide(nom, denom)
```
1) So, matrix P shows us which data suits to which som map node. And I can't understand the matrix S, what for is it? When we do P X training_data -> we sum up components of vectors which has the same bmu, what is the meaning for it? And would be helpful to get description about nom, nV and denom matrices, what for are they?
2)  _distance_matrix  is always the same. If Im not wrong, som's map units should change the distance during the training process, but in implementation this matrix is always the same. Could you explain why?

**Comment by sevamoo** [comment]
As it is written : "... it is based on the implemented algorithm in som toolbox for Matlab by Helsinky University." 
Please, look at the batch training formula at page 9 here: http://www.cis.hut.fi/somtoolbox/package/papers/techrep.pdf
