### ISSUE TITLE
Code crashes when mapszie is [200,200]

### ISSUE THREAD

**Issue by businessglitch** [sevamoo/SOMPY#91]
Hi everyone, I justwanted to check if this is a know issue.

on default when you don't specify mapsize, it sets it to [20,56] but if you want to increase the number of nodes to be trained, you will have to increase the mapsize. I did so and it crashes at [200,200]. 

Is there any reason why this is happening?

**Comment by sevamoo** [comment]
Most likely it is out of memory problem. 200x200 is relatively large and in a normal computer it will crash.  
Also, considering the capacity of SOM as a manifold learning method or some kind of clustering, I really don't think having a very large SOM will really be different in terms of quantization errors or the identified patterns in the SOM. try it with 100x100 and increase the mapsize slowly to see what happens. 
Essentially methods like SOM get stable results with small data sets and also relatively small sizes.
