### ISSUE TITLE
Access Neuron values?

### ISSUE THREAD

**Issue by JackActon** [sevamoo/SOMPY#92]
Hi there,

After the map has been trained by the algorithm, is there any way to acess the neuron weight values? I would like to check what has been stored in specific indexes to see which clusters have been identified from my training set.

Thanks,
Jack

**Comment by businessglitch** [comment]
Hi Jack,

So the way that this works is lets say you have an array of 5000 data points

1) The map size identifies how many data points of the 50,000 should be used for training.
eg: Mapsize = [20,20] therefore 20x20 = 400 data points of 50,000 are going to be used.

2) To get the cluster value of each data point:
cluster_data = sm.cluster(n_clusters=2)
where cluster_data is an array that indicates the cluster value for each data point meaning.

data[0] has a cluster value of cluster_data[0].

I hope that's what you were looking for

**Comment by JackActon** [comment]
For example then, if Im passing multi dimensional vectors instead of individual data points. Each vector is presented to the map, BMU is then found and  that unit and the surrounding ones in the map are updated. Is there some way to acess the values in the cell of the map after it has been trained? Apologies if this is a dumb question.

Your answer allows me to see where each piece of data was put, which is useful to me also but not quite what I was after, so I apologise if i am still unclear.

**Comment by Mind-The-Data** [comment]
@JackActon 
I believe it is sm.codebook.matrix which gives the dimensions of the 'nodes' in the higher dimensional data space.
