### ISSUE TITLE
Rect visualization bug 

### ISSUE THREAD

**Issue by germayneng** [sevamoo/SOMPY#97]
Good day,

There seems to be another bug, in particular, the using rect mode in train and later k-means and  visualizing. This is the end product of the rect visualization using hitmapview.

The color seems to be out of place with the labels:
![image](https://user-images.githubusercontent.com/22788747/50941890-9e625980-14c1-11e9-8d97-d0e6b07ab09c.png)

This seems to be the color mapping associated with the hexa plot: 
The following is training on hexa mode and using k-means
![image](https://user-images.githubusercontent.com/22788747/50941949-d4074280-14c1-11e9-8195-1d1aa4ee08df.png)

I was using the an older version initially (rect visual works) and i believe there might be a chance that there is some bug associated with it. 
Below is the rect mod plotted using the older version. 
![image](https://user-images.githubusercontent.com/22788747/50942023-1466c080-14c2-11e9-93b8-1d044ee0b9b3.png)

**Comment by ricardomourarpm** [comment]
I think the problem is the following:

See in hitmap.py:

    plt.imshow(clusters.reshape(msz[0], msz[1])[::], alpha=0.5)

and replace by:

         plt.imshow(np.flip(clusters.reshape(msz[0], msz[1])[::],axis=0), alpha=0.5)

**Comment by germayneng** [comment]
Possible to push this change to the main master? I believe many people are also having this problem

**Comment by ricardomourarpm** [comment]
https://github.com/ricardomourarpm/SOMPY

This is my version of SOMPY files. Changes from the original made mainly in hitmap.py

Added plot_rect_map for exogenous variables visualization when lattice='rect'

**Comment by sevamoo** [comment]
Could you please, send a pull request regarding these changes?
Best
Vahid
